numpy-1 で作成したnumpyの配列を、それぞれ X1 と X2して定義をして下さい。

In [1]:
import numpy as np  # 前の課題と同様に□にキーワードを入れてください。

In [2]:
X1 = np.array([[1, 2, 3], [4, 5, 6]])
X2 = np.zeros(6).reshape(3, 2)  # 前の課題と同様に□にメソッドを入れてください。

In [3]:
print(X1)
print(X2)

[[1 2 3]
 [4 5 6]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


X2 の全ての要素に、 `2` を加算して下さい。その値を X3として下さい。

In [4]:
X3 = X2 + 2  # □に演算子を入れてください。
print(X3)
assert np.all(X3 == 2)

[[2. 2.]
 [2. 2.]
 [2. 2.]]


X1 と X3 のドット積を計算して下しさい。

In [5]:
X4 = X1 @ X3  # □に演算子を入れてください。
assert np.all(X4 == np.dot(X1, X3))
X4

array([[12., 12.],
       [30., 30.]])