以下の行列をQR分解して下さい。

\begin{pmatrix}
2 & -2 & -1 \\
1 & -1 & 2 \\
-4 & -1 & 2 \\
2 & 3 & -1 \\ 
\end{pmatrix}

In [10]:
import numpy as np
from scipy import linalg

In [11]:
A = np.array([[ 2, -2, -1],[ 1, -1,  2],[-4, -1,  2],[ 2,  3, -2]])  # □にPythonのリストを入れ指定の行列を作ってください。
print(A)

[[ 2 -2 -1]
 [ 1 -1  2]
 [-4 -1  2]
 [ 2  3 -2]]


In [16]:
Q, R = linalg.qr(A)  # □に入る linalg の関数を入れてください

In [17]:
print(Q)

[[-4.00000000e-01 -6.41426981e-01 -4.47213595e-01  4.78091444e-01]
 [-2.00000000e-01 -3.20713490e-01  8.94427191e-01  2.39045722e-01]
 [ 8.00000000e-01 -5.34522484e-02 -5.55111512e-17  5.97614305e-01]
 [-4.00000000e-01  6.94879229e-01 -1.66533454e-16  5.97614305e-01]]


In [18]:
print(R)

[[-5.         -1.          2.4       ]
 [ 0.          3.74165739 -1.49666295]
 [ 0.          0.          2.23606798]
 [ 0.          0.          0.        ]]


求めた、Q及びRの行数及び列数を確認して下しい。

In [19]:
print(Q.shape)
assert Q.shape == (4, 4)
print(R.shape)
assert R.shape == (4, 3)

(4, 4)
(4, 3)


求めた、Q及びRが、A = QR が正しいことを確認して下しい。

In [20]:
np.allclose(A, Q @ R)

True

In [21]:
assert np.allclose(A, Q @ R)